@startuml

[eden-dependencies] --> [eden-architect]
[eden-parent] --> [eden-dependencies]
[eden-commons] --> [eden-parent]
[eden-spring-framework] --> [eden-commons]
[eden-spring-data] --> [eden-spring-framework]
[eden-spring-security] --> [eden-spring-framework]
[eden-spring-integration] --> [eden-spring-framework]
[eden-spring-cloud] --> [eden-spring-framework]
[eden-spring-cloud] --> [eden-spring-security]
[eden-spring-test] --> [eden-spring-framework]
[eden-spring-test] --> [eden-spring-integration]

@enduml
